blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("main.urls"))
]

main/urls.py
from django.urls import path, include
from main import views

urlpatterns = [
    path("", views.index, name="index"),
    path("articles/<int:pk>", views.article, name="get_article"),
    path("author/<int:pk>", views.author, name="get_author"),
    path("articles", views.create_articles, name="create_articles")
]

main/models.py
from django.db import models

# Create your models here.


class Author(models.Model):
    name = models.CharField(max_length=256)
    email = models.EmailField()

    def __str__(self):
        return self.name


class Articles(models.Model):
    title = models.CharField(max_length=256)
    body = models.TextField()
    createdAt = models.DateField(auto_now_add=True)
    authors = models.ManyToManyField(Author)

    def __str__(self):
        return self.title

main/views.py
from django.shortcuts import render, get_object_or_404
from .logics import get_top_10_recent_articles, get_article
from main import models
# Create your views here.


def index(request):
    top_10_recent_articles = get_top_10_recent_articles()
    return render(request, 'main/index.html', {'top_10_recent_articles': top_10_recent_articles})


def article(request, pk):
    article = get_object_or_404(models.Articles, pk=pk)
    context = {
        "article": article
    }

    return render(request, "main/article.html", context)


def author(request, pk):
    author = get_object_or_404(models.Author, pk=pk)
    context = {
        "author": author
    }

    return render(request, "main/author.html", context)


def create_articles(request):
    authors = models.Author.objects.all()
    context = {
        "authors": authors
    }
    if request.method == "POST":
        article_data = {
            "title": request.POST['title'],
            "body": request.POST['content']
        }
        article = models.Articles.objects.create(**article_data)
        author = models.Author.objects.filter(pk=request.POST["authors"])
        article.authors.set(author)
        # author = models.Author.objects.get(pk=request.POST["authors"])
        # article.authors.set([author])
        context["sucess"] = True
    return render(request, "main/create_article.html", context)

templates/main/article.html
{% extends "main/base.html" %} {% block content %}

<h1>{{ article.title }}</h1>
<h3>Created at : {{ article.createdAt }}</h3>
<p>
  Authors: {% for author in article.authors.all %}
  <a href="{% url 'get_author' author.pk %}">
    {{ author.name }} {% if not forloop.last %}, {% endif %} 
  </a>
  {% endfor %}
</p>
<p>{{ article.body }}</p>

{% endblock %}

templates/main/author.html
{% extends "main/base.html" %}
{% block content %}
  <h1>{{ author }}</h1>
  <h5>Email: {{ author.email }}</h5>
  <h4>Articles Written:</h4>
  <ul>
    {% for article in author.articles_set.all %}
      <li><a href="{% url 'get_article' article.id %}"> {{ article.title }} </a></li>
    {% endfor %}
  </ul>
{% endblock %}

templates/main/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{{ request.resolver_match.url_name }}{% endblock %}</title>
</head>
<body>
    {% block content %} {% endblock %}
</body>
</html>

templates/main/create_article.html
{% extends "main/base.html" %}

{% block content %}
<h1>Create article</h1>

{% if sucess %}
    <h4>Article created sucess Fully</h4>
{% endif %}

<form method="post">
    {% csrf_token %}
    <label for="title">Title:</label>
    <input type="text" name="title" id="title">
    <label for="content">Content:</label>
    <textarea name="content" id="content" cols="30" rows="10"></textarea>
    <label for="authors">Author:</label>
    <select name="authors" id="authors">
        {% for author in authors %}
            <option value="{{ author.pk }}">{{ author }}</option>
        {% endfor %}
    </select>
    <input type="submit" value="Create Article">  <!-- Add a submit button -->
    <button type="reset">Reset</button>
</form> 

{% endblock %}

templates/main/index.html
{% extends "main/base.html" %}

{% block content %}
    <h1>Hello my name is priyanshu Kumar</h1>
    {% for article in top_10_recent_articles %}
    <a href="{% url 'get_article' article.pk %}"><h2>{{ article.title }}</h2></a>
    <p>{{ article.body|slice:":10" }}</p>
    <p>Published on: {{ article.createdAt }}</p>
    <p>Authors: {% for author in article.authors.all %}{{ author.name }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>
{% endfor %}

{% endblock %}